### ISSUE TITLE
LICENSE?

### ISSUE THREAD

**Issue by Tsutsukakushi** [smabie/stag#3]
You should add a license for this project. It's kind of useless without it because no one has any permission to do anything with it.

I suggest [GPLv3](http://www.gnu.org/licenses/gpl-3.0.html).

**Comment by Tsutsukakushi** [comment]
I'm stupid. Just now saw the public domain thing. You should add at least optional CC0 in case some people live in a place that doesn't recognize public domain.

**Comment by smabie** [comment]
Good point. I'll also release it under the WTFPL license.

Sent from Outlook Mobile

    _____________________________
